#if UNITY_EDITOR

using System.Collections;
using System.Collections.Generic;
using UnityEditor;
using UnityEngine;

namespace Artimech
{
    public class editorStateMachineExample : artimechEditorBase
    {
        public editorStateMachineExample() : base()
        {

        }

        [MenuItem("Window/Artimech/ExampleEditor")]
        static void ShowEditor()
        {
            //geolan: hack
            //EditorWindow.GetWindow<artimechEditorExample>();
        }

        new void OnEnable()
        {
            base.OnEnable();
            CreateStates();
        }

        // Use this for initialization
        new void Start()
        {
            base.Start();
        }

        // Update is called once per frame
        new void Update()
        {
            base.Update();
        }

        new void FixedUpdate()
        {
            base.FixedUpdate();
        }

        new void OnGUI()
        {
            base.OnGUI();
        }

        /// <summary>
        /// Autogenerated state are created here inside this function.
        /// </summary>
        void CreateStates()
        {

            m_CurrentState = AddState(new stateEditorExample(this), "stateEditorExample");

            //<ArtiMechStates>

        }
    }
}
#endif